### ISSUE TITLE
About the best model parameters

### ISSUE THREAD

**Issue by lyy66666** [emadeldeen24/AttnSleep#10]
Hello, I reproduced your experimental results and found that the effect was somewhat different from the results in the paper, can you share the pth file that has been trained in your paper?

**Comment by emadeldeen24** [comment]
Can you please illustrate how much different?
Because `somewhat` different gives me an impression of not being a significant difference. And in this case, this could be due to the different train/test splits or the Pytorch/hardware versions. You can train for than once and take the average.

**Comment by lyy66666** [comment]
Okay, thanks for the suggestion, my environment configuration is the same as yours, but there is a 2% error in the result, I will try to run it again and take the average of the results. best regardsOkay, thanks for the suggestion, my environment configuration is the same as yours, but there is a 2% error in the result, I will try to run it again and take the average of the results. best regards

**Comment by lyy66666** [comment]
Okay, thanks for the suggestion, my environment configuration is the same as yours, but there is a 2% error in the result, I will try to run it again and take the average of the results. best regards
