### ISSUE TITLE
About val_accuracy

### ISSUE THREAD

**Issue by JIAAA-z** [emadeldeen24/AttnSleep#11]
We found that the val_accuracy of your code output is inconsistent with the val_accuracy we calculate directly from outs_x.npy/trgs_x.npy.

**Comment by JIAAA-z** [comment]
When epoch=1, the metrics obtained using the outs_x.npy/trgs_x.npy file do not match the indicators output by your source code

**Comment by emadeldeen24** [comment]
please contact me on my email with your results to check if there's something wrong
