### ISSUE TITLE
How did you calculate the final result?

### ISSUE THREAD

**Issue by v-nhandt21** [emadeldeen24/AttnSleep#12]
Thanks for your repo, I am reproducing your code, I have trained the model successfully, 

![image](https://github.com/emadeldeen24/AttnSleep/assets/36092323/434fd66e-1faa-480f-a4eb-18ba962a47d6)

But how did I can calculate the result in in your report, will I use outs.npy and trgs.npy ? Can you provide code for this:

![image](https://github.com/emadeldeen24/AttnSleep/assets/36092323/12a02456-5caf-4257-bf6c-3df0cd332d1b)

**Comment by color4-alt** [comment]
Just the mean of highest val_accuracy in every folds.
