### ISSUE TITLE
About the MF1

### ISSUE THREAD

**Issue by color4-alt** [emadeldeen24/AttnSleep#13]
I calculated the mean of highest val_f1 of every fold, but I can't get the number in your paper which is much higher than I calculated. I wonder how the calculate this metric. Thank you!

**Comment by color4-alt** [comment]
OK, fine. I got it. There is a fatal mistake in `model/metric.py line 18`. `return f1_score(pred.cpu().numpy(), target.data.cpu().numpy(), average='macro')` should be changed to `return f1_score(target.data.cpu().numpy(), pred.cpu().numpy(), average='macro')`. Hope you update it as soon as possible.

**Comment by color4-alt** [comment]
OK,fine. I have known that my way is wrong and the right way is to use the `outs_n.py` and `trgs_n.py`. I deeply read the code, and find that `val_f1` is much lower than expected one because the validation dataset is devide into mutiple batches , and the log `val_f1` is  the avrage of multiple batches' f1. It's difficult to fix this bug, so I suggest you should remind readers in the `README.md`.

**Comment by mochenxin000** [comment]
> OK,fine. I have known that my way is wrong and the right way is to use the and . I deeply read the code, and find that is much lower than expected one because the validation dataset is devide into mutiple batches , and the log is the avrage of multiple batches' f1. It's difficult to fix this bug, so I suggest you should remind readers in the .`outs_n.py``trgs_n.py``val_f1``val_f1``README.md`

Hi，
I found that my F1 rating is exceptionally low and would like to ask why this is. Can you give me some advice? I would appreciate it

**Comment by color4-alt** [comment]
First, you should check the `config.json` especially the `batchsize`. Then, the MF1 in paper is calculating 20 folds prediction together, so you should use the  use the `outs_n.npy` and `trgs_n.npy` files to calculate.

**Comment by mochenxin000** [comment]
I think I understand something. Thank you very much. Is it convenient to add your wechat account? I'd also like to ask about the details. My wechat: mochenxin0710



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/01/2024 09:49 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [emadeldeen24/AttnSleep] About the MF1 (Issue #13) |

First, you should check the config.json especially the batchsize. Then, the MF1 in paper is calculating 20 folds prediction together, so you should use the use the outs_n.npy and trgs_n.npy files to calculate.

**Comment by mochenxin000** [comment]
> First, you should check the `config.json` especially the `batchsize`. Then, the MF1 in paper is calculating 20 folds prediction together, so you should use the use the `outs_n.npy` and `trgs_n.npy` files to calculate.

I think I understand something. Thank you very much. Is it convenient to add your wechat account? I'd also like to ask about the details. My wechat: mochenxin0710
