### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by SunQuantao0** [emadeldeen24/AttnSleep#15]
Hello author,When running the code you provide,The video memory is too large,sleepedf20The dataset reaches 20G,Directly stuck,Does the author have a good solution?,Thank you

**Comment by emadeldeen24** [comment]
Can you please share more details about it?

**Comment by SunQuantao0** [comment]
When I use the sleepedf20 dataset to perform operations on 4090, its video memory occupation reaches 20G, I think it is a bit too big, switch to sleepedf78 dataset, 24G of 4090 is no longer enough to report the error out of memory.  I don't know if you can give some advice on this situation,I wonder if you can give some advice on this situation and  I would appreciate it




---- Replied Message ----
| From | Emadeldeen ***@***.***> |
| Date | 2/26/2024 22:14 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [emadeldeen24/AttnSleep] out of memory (Issue #15) |

Can you please share more details about it?

**Comment by emadeldeen24** [comment]
Try to load a subset of the data and see if it works. If it worked, then your hardware is limited and can't handle the whole data. Maybe you should upgrade the GPU card.

**Comment by SunQuantao0** [comment]
ok thank you
---- Replied Message ----
| From | Emadeldeen ***@***.***> |
| Date | 03/01/2024 14:27 |
| To | emadeldeen24/AttnSleep ***@***.***> |
| Cc | SunQuantao0 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [emadeldeen24/AttnSleep] out of memory (Issue #15) |

Try to load a subset of the data and see if it works. If it worked, then your hardware is limited and can't handle the whole data. Maybe you should upgrade the GPU card.
