### ISSUE TITLE
Recall rate, F1 rating

### ISSUE THREAD

**Issue by mochenxin000** [emadeldeen24/AttnSleep#16]
Hi
I'm a novice, and I've successfully reproduced your code.
Thanks a lot for that, but I would like to know how to display the F1 score and kapaa coefficient, as well as the accuracy and recall rate of each stage, can you help me or help me improve your code?
Thanks very much

**Comment by anlan-he** [comment]
Hello! I am also interested in this work. In train_Kflod.py, there is something confusing. 
data_loader, valid_data_loader, data_count = data_generator_np(folds_data[fold_id][0], folds_data[fold_id][1], batch_size)
For this code, I find that this function just inputs one set of folds_data. Such as in edf-20 dataset, by default, folds_data has 20 sets of data, and all of them should be passed to the function. I wonder if there should be a loop operation here. How do you overcome this problem? 
And if we set fold_id = 20, the index will be out of range. 
Thank you very much. I am looking forward your reply.

**Comment by emadeldeen24** [comment]
@mochenxin000 Hi,
All the metrics can be calculated in [this function](https://github.com/emadeldeen24/AttnSleep/blob/6b4d2665884628c8a7bb09f36589a8ec0992f8e2/base/base_trainer.py#L182).
However, I think the classification report generated at the end already have these metrics.

**Comment by emadeldeen24** [comment]
@anlan-he Hi,
the loop is already there in the [batch_train.sh](https://github.com/emadeldeen24/AttnSleep/blob/main/batch_train.sh).

**Comment by mochenxin000** [comment]
> @mochenxin000 Hi, All the metrics can be calculated in [this function](https://github.com/emadeldeen24/AttnSleep/blob/6b4d2665884628c8a7bb09f36589a8ec0992f8e2/base/base_trainer.py#L182). However, I think the classification report generated at the end already have these metrics.

Hi，emadeldeen
Thank you for your response, but there seems to be only one log file. I did not find the final classification report, I can only see the accuracy rate, and I did not find other indicators. Can you guide me again? Or you can look at the code again, whether less upload things?
I look forward to your reply.

**Comment by anlan-he** [comment]
Oh! I understand. Thank you.

**Comment by emadeldeen24** [comment]
@mochenxin000 

The log file of each fold is found in the fold directory inside the save_dir.
The final classification report is found in the experiment directory, but it is calculated once after all the folds are done [check here](https://github.com/emadeldeen24/AttnSleep/blob/6b4d2665884628c8a7bb09f36589a8ec0992f8e2/base/base_trainer.py#L110), as it sums up all the folds results to calculate the metrics.

**Comment by mochenxin000** [comment]
> @mochenxin000
> 
> The log file of each fold is found in the fold directory inside the save_dir. The final classification report is found in the experiment directory, but it is calculated once after all the folds are done [check here](https://github.com/emadeldeen24/AttnSleep/blob/6b4d2665884628c8a7bb09f36589a8ec0992f8e2/base/base_trainer.py#L110), as it sums up all the folds results to calculate the metrics.

Hi，
I found the log file, but it's just accuracy, nothing else. Should I do something else? I also found a directory called Exp1 but it only kept some logs and so on. Can you give me a hint or some other guidance? I would appreciate it.

**Comment by mochenxin000** [comment]
> Hello! I am also interested in this work. In train_Kflod.py, there is something confusing. data_loader, valid_data_loader, data_count = data_generator_np(folds_data[fold_id][0], folds_data[fold_id][1], batch_size) For this code, I find that this function just inputs one set of folds_data. Such as in edf-20 dataset, by default, folds_data has 20 sets of data, and all of them should be passed to the function. I wonder if there should be a loop operation here. How do you overcome this problem? And if we set fold_id = 20, the index will be out of range. Thank you very much. I am looking forward your reply.

Hi，
I also encountered this problem, I wonder if you have solved it? Can you share your experience? I thought it would be okay, but then it turns out it's the same problem

**Comment by emadeldeen24** [comment]
@mochenxin000 did you run the 20 folds?
you should run the 20 folds (fold 20 should be the last), then after they are all done, you will get the report. Otherwise, you can update the code to generate the report after running each fold.

**Comment by mochenxin000** [comment]
> @mochenxin000 did you run the 20 folds? you should run the 20 folds (fold 20 should be the last), then after they are all done, you will get the report. Otherwise, you can update the code to generate the report after running each fold.
Hi,
I ran the cross-validation 20 times but he only ran it once and reported an error. I don't know why.

**Comment by emadeldeen24** [comment]
please stick with the procedure in the README file, use [batch_train.sh](https://github.com/emadeldeen24/AttnSleep/blob/main/batch_train.sh) and you should get the results correctly.
