### ISSUE TITLE
train_Kfold.py

### ISSUE THREAD

**Issue by anlan-he** [emadeldeen24/AttnSleep#17]
data_loader, valid_data_loader, data_count = data_generator_np(folds_data[fold_id][0], folds_data[fold_id][1], batch_size)
For this code, I find that this function just inputs one set of folds_data. Such as in edf-20 dataset, by default, folds_data has 20 sets of data, and all of them should be passed to the function. I wonder if there should be a loop operation here. And in the output xlsx file, all values are equal to 0. Could you please help me solve this problem? Thanks a lot.

**Comment by ngocnh22** [comment]
I also follow the README. But I cant run this code. in prepare_shhs.py which is the data_dir and ann_dir. Thank you for your answer.

**Comment by anlan-he** [comment]
Sorry, I used the preprocessed data provided by the author, so I haven't read the prepare.py carefully. How do you set the value of fold_id? Do you make it be equal to the number of subjects?

**Comment by ngocnh22** [comment]
Can you share with me? how to run this code. I am trying step by step but I am stuck at preparing for training dataset(cd prepare_datasets
python prepare_physionet.py --data_dir /path/to/PSG/files --output_dir edf_20_npz --select_ch "EEG Fpz-Cz"
python prepare_shhs.py --data_dir /path/to/EDF/files --ann_dir /path/to/Annotation/files --output_dir shhs_npz --select_ch "EEG C4-A1"

**Comment by anlan-he** [comment]
I suggest that you can use the preprocessed data and make your own path, then you can run train file directly.

**Comment by ngocnh22** [comment]
can you share your folder? I make sure I am correct on the path side.

**Comment by anlan-he** [comment]
\AttnSleep-main\prepare_datasets\data_edf_20_npz\fpzcz
This is my path.

**Comment by ngocnh22** [comment]
which files in the fpzcz? Sleepedf-20 I downloaded files as the SC4001E0-PSG.edf, SC4001EC-Hypnogram.edf, and etc.

**Comment by anlan-he** [comment]
![屏幕截图 2024-03-27 194150](https://github.com/emadeldeen24/AttnSleep/assets/77526316/f23afc50-f054-4446-a33a-f5e9065404d7)
This link, there are three preprocessed datasets.

**Comment by ngocnh22** [comment]
And then, how about the file prepapre_shhs.py 
--data_dir /path/to/EDF/files --> ?
--ann_dir /path/to/Annotation/files  --> ?
--output_dir shhs_npz 
--select_ch "EEG C4-A1"

**Comment by anlan-he** [comment]
If you download those preprocessed datasets, then you don't need run these two prepare.py files. You can skip this step.

**Comment by ngocnh22** [comment]
this is the output after I run.  python train_Kfold_CV.py --device 0 --fold_id 10 --np_data_dir data_edf_20_npz\fpzcz

![image](https://github.com/emadeldeen24/AttnSleep/assets/52875248/f2fcf1e4-70c5-4045-b2dd-4550d1958a7f)

**Comment by anlan-he** [comment]
Please show your files in data_edf_20_npz\fpzcz

**Comment by ngocnh22** [comment]
![Uploading image.png…]()

**Comment by ngocnh22** [comment]
![image](https://github.com/emadeldeen24/AttnSleep/assets/52875248/cfc60d51-d79f-4e55-a53c-fb9de7e42255)

**Comment by anlan-he** [comment]
Your path is wrong. where is your train.py?

**Comment by ngocnh22** [comment]
![image](https://github.com/emadeldeen24/AttnSleep/assets/52875248/3ace5984-2e82-4b53-880d-34fe3720f3cd)
my folder is constructed is like that.

**Comment by anlan-he** [comment]
According to your last picture, your path should be ./prepare_datasets/data_edf_20_npz/fpzcz

**Comment by ngocnh22** [comment]
it appears new one. It is actually difficult.
![image](https://github.com/emadeldeen24/AttnSleep/assets/52875248/71d30644-c615-4590-98b6-0d19093781b6)

**Comment by anlan-he** [comment]
I haven't encountered this problem. It's so hard.

**Comment by emadeldeen24** [comment]
Hi @anlan-he and @ngocnh22.
Can you please reply to this comment with more specific questions to address your issues?
Thanks.
