### ISSUE TITLE
Possible bug when preprocessing the sleep edf dataset

### ISSUE THREAD

**Issue by likith012** [emadeldeen24/AttnSleep#3]
I believe [this line](https://github.com/emadeldeen24/AttnSleep/blob/main/prepare_datasets/prepare_physionet.py#L95) should have the argument set to `scaling` instead of `scaling_time`. It is throwing me an error if I use that argument and couldn't find any documentation too. What does this particular line do?

**Comment by emadeldeen24** [comment]
To avoid this issue, please consider installing similar mne version as ours (mne=='0.20.7' as mentioned in the README).   
For more info about it please check its [online documentation](https://mne.tools/0.20/generated/mne.io.Raw.html?highlight=to_data_frame#mne.io.Raw.to_data_frame).
