### ISSUE TITLE
Subjects getting wrong year in header data

### ISSUE THREAD

**Issue by likith012** [emadeldeen24/AttnSleep#4]
At [this line](https://github.com/emadeldeen24/AttnSleep/blob/eb2beeb5bb57c6244fecb3cf5b6f7bcdab64e9f1/prepare_datasets/dhedfreader.py#L48), I believe you need to replace `2000`  with `1900`

**Comment by emadeldeen24** [comment]
I'm not sure why you think so.

**Comment by likith012** [comment]
The variable `year` is giving for a particular subject as 89 and since all the recordings are recorded in 1989. But I noticed this doesn't affect anywhere in the entire code.

**Comment by likith012** [comment]
I noticed at [MRCNN implementatio](https://github.com/emadeldeen24/AttnSleep/blob/eb2beeb5bb57c6244fecb3cf5b6f7bcdab64e9f1/model/model.py#L137-L140) you concatenating the `time points` from the two different CNN paths of shapes `(B, 128, 64)` and `(B, 128, 16)` respectively. Don't you think by doing this we lose the temporal information because of the temporal split that is happening after the `64th` time point, instead of that can we concatenate the features(after interpolating the time points)?

**Comment by emadeldeen24** [comment]
We don't lose the temporal information. We extract different features in each branch (with using different kernel sizes and strides), and each is keeping its temporal information. With concatenating them at last, we get richer information to help in the next modules.

**Comment by likith012** [comment]
Hey can you help me out here, I am a bit confused about the attention module you are using. The output from the MRCNN modules are `(B, 128, 64)` and `B, 128, 16)` in the form of `(B, C, T)` here `C` is `num_channels` and `T` is `num_time_points`. You are concatenating across the time points, the output is `(B, 128, 80)` and you apply an AFR module, then the output is `B, 30, 80` of the form `B, C, T`.  But when applying the MHA module i.e, the self-attention module for obtaining the representation subspaces for multiple heads you considering the dimension as 80 which is `T`, so you are getting individual heads by splitting across the time samples i.e, `80 // num_heads`. And in the transformer model, they split across the channel dimensions i.e, `C` = 30. So it should be `30 // num_heads`

**Comment by emadeldeen24** [comment]
>  So it should be `30 // num_heads`   

This is not correct, but I understand it can be tricky when mapping between NLP and EEG data.   
Please check https://towardsdatascience.com/transformers-explained-visually-part-3-multi-head-attention-deep-dive-1c1ff1024853.

**Comment by likith012** [comment]
In the language task, we have data of form `(B, T, C)`, they split the `C` into multiple smaller features(subspaces) and learn these subspaces individually and aggregate them. Here in the EEG domain with data of form `(B, C, T)` are you trying to split the `T` into multiple smaller time points i.e, `T // num_heads` (model has access to complete features for each smaller time subspace in this case). By doing so the model can learn smaller time point subspaces individually and aggregate them at the end.

**Comment by likith012** [comment]
@emadeldeen24 Can you comment on the above question.

**Comment by emadeldeen24** [comment]
> Here in the EEG domain with data of form (B, C, T) are you trying to split the T into multiple smaller time points i.e, T // num_heads (model has access to complete features for each smaller time subspace in this case). By doing so the model can learn smaller time point subspaces individually and aggregate them at the end.

This is correct. But you can also test splitting them in channels `C` instead of time points `T` and see how the performance changes.

**Comment by likith012** [comment]
Thanks for the clarification, will try to experiment replacing `T` with `C`
