### ISSUE TITLE
question about the Class-Aware Loss Function and Optimization

### ISSUE THREAD

**Issue by MatrixWP** [emadeldeen24/AttnSleep#5]
In your paper, the weight of classes is <a href="https://www.codecogs.com/eqnedit.php?latex=w_k=\mu_k&space;\cdot&space;max(1,&space;log(\mu_kM/M_k))" target="_blank"><img src="https://latex.codecogs.com/gif.latex?w_k=\mu_k&space;\cdot&space;max(1,&space;log(\mu_kM/M_k))" title="w_k=\mu_k \cdot max(1, log(\mu_kM/M_k))" /></a>, but in your code, it seems like the formula is<a href="https://www.codecogs.com/eqnedit.php?latex=w_k=1/N&space;\cdot&space;max(1,&space;log(\mu_kM/M_k))" target="_blank"><img src="https://latex.codecogs.com/gif.latex?w_k=1/N&space;\cdot&space;max(1,&space;log(\mu_kM/M_k))" title="w_k=1/N \cdot max(1, log(\mu_kM/M_k))" /></a>(N is the number of classes), I wonder if the code below is right?
https://github.com/emadeldeen24/AttnSleep/blob/eb2beeb5bb57c6244fecb3cf5b6f7bcdab64e9f1/utils/util.py#L73

**Comment by emadeldeen24** [comment]
I updated it. Thank you for your comment.
