### ISSUE TITLE
Saving best model

### ISSUE THREAD

**Issue by mostafashahin** [emadeldeen24/AttnSleep#7]
https://github.com/emadeldeen24/AttnSleep/blob/2c3bb127b066b32ee7530da5ee87e81cc3eaa10b/base/base_trainer.py#L78

The "best" variable should be initially "False" and set to "True" if the metric improved 

`best = True` should be `best = False`

Otherwise, the code will save the model each save_period epochs regardless if improved or not.

Regards,
Mostafa

**Comment by emadeldeen24** [comment]
Noted with thanks!
