### ISSUE TITLE
ValueError: Names should be an ordered collection.

### ISSUE THREAD

**Issue by 427smx** [emadeldeen24/AttnSleep#8]
Hi, thanks for sharing the code open-source!
prepare_shhs.py This file keeps appearing‘ ValueError: Names should be an ordered collection.’ this question，Is it because I downloaded a public dataset, not the dataset you preprocessed? Can you help me out?

**Comment by emadeldeen24** [comment]
Can you post the full error message?

**Comment by emadeldeen24** [comment]
I will close due to inactivity

**Comment by ngocnh22** [comment]
![image](https://github.com/emadeldeen24/AttnSleep/assets/52875248/18902503-bf48-4684-b44e-2e4333d337c2)
